// This file was generated by gir (7484d29) from gir-files (71d73f0)
// DO NOT EDIT

use DOMCharacterData;
use DOMEventTarget;
use DOMNode;
use DOMObject;
use DOMText;
use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DOMCDATASection(Object<ffi::WebKitDOMCDATASection>): DOMText, DOMCharacterData, DOMNode, DOMObject, DOMEventTarget;

    match fn {
        get_type => || ffi::webkit_dom_cdata_section_get_type(),
    }
}

impl DOMCDATASection {}
