// This file was generated by gir (074a1ca) from gir-files (???)
// DO NOT EDIT

use ffi;
use glib::translate::*;

glib_wrapper! {
    pub struct DOMDocumentFragment(Object<ffi::WebKitDOMDocumentFragment>);

    match fn {
        get_type => || ffi::webkit_dom_document_fragment_get_type(),
    }
}

impl DOMDocumentFragment {}
