// This file was generated by gir (https://github.com/gtk-rs/gir @ f5fca82)
// from gir-files (https://github.com/gtk-rs/gir-files @ b8f5ef1)
// DO NOT EDIT

use DOMCSSRule;
use DOMObject;
use Error;
use ffi;
use glib;
use glib::object::Downcast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use libc;
use std::boxed::Box as Box_;
use std::mem;
use std::mem::transmute;
use std::ptr;

glib_wrapper! {
    pub struct DOMCSSStyleDeclaration(Object<ffi::WebKitDOMCSSStyleDeclaration, ffi::WebKitDOMCSSStyleDeclarationClass>): DOMObject;

    match fn {
        get_type => || ffi::webkit_dom_css_style_declaration_get_type(),
    }
}

pub trait DOMCSSStyleDeclarationExt {
    fn get_css_text(&self) -> Option<String>;

    fn get_length(&self) -> libc::c_ulong;

    fn get_parent_rule(&self) -> Option<DOMCSSRule>;

    fn get_property_priority(&self, propertyName: &str) -> Option<String>;

    fn get_property_shorthand(&self, propertyName: &str) -> Option<String>;

    fn get_property_value(&self, propertyName: &str) -> Option<String>;

    fn is_property_implicit(&self, propertyName: &str) -> bool;

    fn item(&self, index: libc::c_ulong) -> Option<String>;

    fn remove_property(&self, propertyName: &str) -> Result<String, Error>;

    fn set_css_text(&self, value: &str) -> Result<(), Error>;

    fn set_property(&self, propertyName: &str, value: &str, priority: &str) -> Result<(), Error>;

    fn connect_property_css_text_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_length_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_parent_rule_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<DOMCSSStyleDeclaration> + IsA<glib::object::Object>> DOMCSSStyleDeclarationExt for O {
    fn get_css_text(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_css_style_declaration_get_css_text(self.to_glib_none().0))
        }
    }

    fn get_length(&self) -> libc::c_ulong {
        unsafe {
            ffi::webkit_dom_css_style_declaration_get_length(self.to_glib_none().0)
        }
    }

    fn get_parent_rule(&self) -> Option<DOMCSSRule> {
        unsafe {
            from_glib_full(ffi::webkit_dom_css_style_declaration_get_parent_rule(self.to_glib_none().0))
        }
    }

    fn get_property_priority(&self, propertyName: &str) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_css_style_declaration_get_property_priority(self.to_glib_none().0, propertyName.to_glib_none().0))
        }
    }

    fn get_property_shorthand(&self, propertyName: &str) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_css_style_declaration_get_property_shorthand(self.to_glib_none().0, propertyName.to_glib_none().0))
        }
    }

    fn get_property_value(&self, propertyName: &str) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_css_style_declaration_get_property_value(self.to_glib_none().0, propertyName.to_glib_none().0))
        }
    }

    fn is_property_implicit(&self, propertyName: &str) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_css_style_declaration_is_property_implicit(self.to_glib_none().0, propertyName.to_glib_none().0))
        }
    }

    fn item(&self, index: libc::c_ulong) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_css_style_declaration_item(self.to_glib_none().0, index))
        }
    }

    fn remove_property(&self, propertyName: &str) -> Result<String, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_css_style_declaration_remove_property(self.to_glib_none().0, propertyName.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn set_css_text(&self, value: &str) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::webkit_dom_css_style_declaration_set_css_text(self.to_glib_none().0, value.to_glib_none().0, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn set_property(&self, propertyName: &str, value: &str, priority: &str) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::webkit_dom_css_style_declaration_set_property(self.to_glib_none().0, propertyName.to_glib_none().0, value.to_glib_none().0, priority.to_glib_none().0, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn connect_property_css_text_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::css-text",
                transmute(notify_css_text_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_length_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::length",
                transmute(notify_length_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_parent_rule_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::parent-rule",
                transmute(notify_parent_rule_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

unsafe extern "C" fn notify_css_text_trampoline<P>(this: *mut ffi::WebKitDOMCSSStyleDeclaration, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<DOMCSSStyleDeclaration> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&DOMCSSStyleDeclaration::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_length_trampoline<P>(this: *mut ffi::WebKitDOMCSSStyleDeclaration, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<DOMCSSStyleDeclaration> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&DOMCSSStyleDeclaration::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_parent_rule_trampoline<P>(this: *mut ffi::WebKitDOMCSSStyleDeclaration, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<DOMCSSStyleDeclaration> {
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&DOMCSSStyleDeclaration::from_glib_borrow(this).downcast_unchecked())
}
