// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use DOMElement;
use DOMEventTarget;
use DOMHTMLElement;
use DOMNode;
use DOMObject;
use glib::GString;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect_raw;
use glib::translate::*;
use glib_sys;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use webkit2_webextension_sys;

glib_wrapper! {
    pub struct DOMHTMLModElement(Object<webkit2_webextension_sys::WebKitDOMHTMLModElement, webkit2_webextension_sys::WebKitDOMHTMLModElementClass, DOMHTMLModElementClass>) @extends DOMHTMLElement, DOMElement, DOMNode, DOMObject, @implements DOMEventTarget;

    match fn {
        get_type => || webkit2_webextension_sys::webkit_dom_html_mod_element_get_type(),
    }
}

pub const NONE_DOMHTML_MOD_ELEMENT: Option<&DOMHTMLModElement> = None;

pub trait DOMHTMLModElementExt: 'static {
    #[cfg_attr(feature = "v2_22", deprecated)]
    fn get_cite(&self) -> Option<GString>;

    #[cfg_attr(feature = "v2_22", deprecated)]
    fn get_date_time(&self) -> Option<GString>;

    #[cfg_attr(feature = "v2_22", deprecated)]
    fn set_cite(&self, value: &str);

    #[cfg_attr(feature = "v2_22", deprecated)]
    fn set_date_time(&self, value: &str);

    fn connect_property_cite_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_date_time_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<DOMHTMLModElement>> DOMHTMLModElementExt for O {
    fn get_cite(&self) -> Option<GString> {
        unsafe {
            from_glib_full(webkit2_webextension_sys::webkit_dom_html_mod_element_get_cite(self.as_ref().to_glib_none().0))
        }
    }

    fn get_date_time(&self) -> Option<GString> {
        unsafe {
            from_glib_full(webkit2_webextension_sys::webkit_dom_html_mod_element_get_date_time(self.as_ref().to_glib_none().0))
        }
    }

    fn set_cite(&self, value: &str) {
        unsafe {
            webkit2_webextension_sys::webkit_dom_html_mod_element_set_cite(self.as_ref().to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_date_time(&self, value: &str) {
        unsafe {
            webkit2_webextension_sys::webkit_dom_html_mod_element_set_date_time(self.as_ref().to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn connect_property_cite_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::cite\0".as_ptr() as *const _,
                Some(transmute(notify_cite_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }

    fn connect_property_date_time_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::date-time\0".as_ptr() as *const _,
                Some(transmute(notify_date_time_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }
}

unsafe extern "C" fn notify_cite_trampoline<P, F: Fn(&P) + 'static>(this: *mut webkit2_webextension_sys::WebKitDOMHTMLModElement, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
where P: IsA<DOMHTMLModElement> {
    let f: &F = &*(f as *const F);
    f(&DOMHTMLModElement::from_glib_borrow(this).unsafe_cast())
}

unsafe extern "C" fn notify_date_time_trampoline<P, F: Fn(&P) + 'static>(this: *mut webkit2_webextension_sys::WebKitDOMHTMLModElement, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
where P: IsA<DOMHTMLModElement> {
    let f: &F = &*(f as *const F);
    f(&DOMHTMLModElement::from_glib_borrow(this).unsafe_cast())
}

impl fmt::Display for DOMHTMLModElement {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "DOMHTMLModElement")
    }
}
