// This file was generated by gir (0f7cd61) from gir-files (857b8f5)
// DO NOT EDIT

use DOMElement;
use DOMEventTarget;
use DOMFileList;
use DOMHTMLElement;
use DOMHTMLFormElement;
use DOMNode;
use DOMObject;
use Error;
use ffi;
use glib;
use glib::Value;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use libc;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DOMHTMLInputElement(Object<ffi::WebKitDOMHTMLInputElement>): DOMHTMLElement, DOMElement, DOMNode, DOMObject, DOMEventTarget;

    match fn {
        get_type => || ffi::webkit_dom_html_input_element_get_type(),
    }
}

pub trait DOMHTMLInputElementExt {
    fn get_accept(&self) -> Option<String>;

    fn get_align(&self) -> Option<String>;

    fn get_alt(&self) -> Option<String>;

    #[cfg(feature = "v2_16")]
    fn get_auto_filled(&self) -> bool;

    fn get_autofocus(&self) -> bool;

    fn get_capture(&self) -> bool;

    #[cfg(feature = "v2_14")]
    fn get_capture_type(&self) -> Option<String>;

    fn get_checked(&self) -> bool;

    fn get_default_checked(&self) -> bool;

    fn get_default_value(&self) -> Option<String>;

    fn get_disabled(&self) -> bool;

    fn get_files(&self) -> Option<DOMFileList>;

    fn get_form(&self) -> Option<DOMHTMLFormElement>;

    fn get_height(&self) -> libc::c_ulong;

    fn get_indeterminate(&self) -> bool;

    fn get_input_type(&self) -> Option<String>;

    fn get_max_length(&self) -> libc::c_long;

    fn get_multiple(&self) -> bool;

    fn get_name(&self) -> Option<String>;

    #[cfg(feature = "v2_16")]
    fn get_read_only(&self) -> bool;

    fn get_size(&self) -> libc::c_ulong;

    fn get_src(&self) -> Option<String>;

    fn get_use_map(&self) -> Option<String>;

    fn get_value(&self) -> Option<String>;

    fn get_width(&self) -> libc::c_ulong;

    fn get_will_validate(&self) -> bool;

    fn is_edited(&self) -> bool;

    fn select(&self);

    fn set_accept(&self, value: &str);

    fn set_align(&self, value: &str);

    fn set_alt(&self, value: &str);

    #[cfg(feature = "v2_16")]
    fn set_auto_filled(&self, value: bool);

    fn set_autofocus(&self, value: bool);

    #[cfg(feature = "v2_16")]
    fn set_capture_type(&self, value: &str);

    fn set_checked(&self, value: bool);

    #[cfg(feature = "v2_16")]
    fn set_default_checked(&self, value: bool);

    fn set_default_value(&self, value: &str);

    fn set_disabled(&self, value: bool);

    #[cfg(feature = "v2_16")]
    fn set_editing_value(&self, value: &str);

    fn set_files(&self, value: &DOMFileList);

    fn set_height(&self, value: libc::c_ulong);

    fn set_indeterminate(&self, value: bool);

    fn set_input_type(&self, value: &str);

    fn set_max_length(&self, value: libc::c_long) -> Result<(), Error>;

    fn set_multiple(&self, value: bool);

    fn set_name(&self, value: &str);

    fn set_read_only(&self, value: bool);

    fn set_size(&self, value: libc::c_ulong) -> Result<(), Error>;

    fn set_src(&self, value: &str);

    fn set_use_map(&self, value: &str);

    fn set_value(&self, value: &str);

    fn set_width(&self, value: libc::c_ulong);

    fn set_property_capture(&self, capture: Option<&str>);

    fn set_property_default_checked(&self, default_checked: bool);

    fn get_property_read_only(&self) -> bool;

    fn get_property_type(&self) -> Option<String>;

    fn set_property_type(&self, type_: Option<&str>);
}

impl<O: IsA<DOMHTMLInputElement> + IsA<glib::object::Object>> DOMHTMLInputElementExt for O {
    fn get_accept(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_accept(self.to_glib_none().0))
        }
    }

    fn get_align(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_align(self.to_glib_none().0))
        }
    }

    fn get_alt(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_alt(self.to_glib_none().0))
        }
    }

    #[cfg(feature = "v2_16")]
    fn get_auto_filled(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_auto_filled(self.to_glib_none().0))
        }
    }

    fn get_autofocus(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_autofocus(self.to_glib_none().0))
        }
    }

    fn get_capture(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_capture(self.to_glib_none().0))
        }
    }

    #[cfg(feature = "v2_14")]
    fn get_capture_type(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_capture_type(self.to_glib_none().0))
        }
    }

    fn get_checked(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_checked(self.to_glib_none().0))
        }
    }

    fn get_default_checked(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_default_checked(self.to_glib_none().0))
        }
    }

    fn get_default_value(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_default_value(self.to_glib_none().0))
        }
    }

    fn get_disabled(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_disabled(self.to_glib_none().0))
        }
    }

    fn get_files(&self) -> Option<DOMFileList> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_files(self.to_glib_none().0))
        }
    }

    fn get_form(&self) -> Option<DOMHTMLFormElement> {
        unsafe {
            from_glib_none(ffi::webkit_dom_html_input_element_get_form(self.to_glib_none().0))
        }
    }

    fn get_height(&self) -> libc::c_ulong {
        unsafe {
            ffi::webkit_dom_html_input_element_get_height(self.to_glib_none().0)
        }
    }

    fn get_indeterminate(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_indeterminate(self.to_glib_none().0))
        }
    }

    fn get_input_type(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_input_type(self.to_glib_none().0))
        }
    }

    fn get_max_length(&self) -> libc::c_long {
        unsafe {
            ffi::webkit_dom_html_input_element_get_max_length(self.to_glib_none().0)
        }
    }

    fn get_multiple(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_multiple(self.to_glib_none().0))
        }
    }

    fn get_name(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_name(self.to_glib_none().0))
        }
    }

    #[cfg(feature = "v2_16")]
    fn get_read_only(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_read_only(self.to_glib_none().0))
        }
    }

    fn get_size(&self) -> libc::c_ulong {
        unsafe {
            ffi::webkit_dom_html_input_element_get_size(self.to_glib_none().0)
        }
    }

    fn get_src(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_src(self.to_glib_none().0))
        }
    }

    fn get_use_map(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_use_map(self.to_glib_none().0))
        }
    }

    fn get_value(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_input_element_get_value(self.to_glib_none().0))
        }
    }

    fn get_width(&self) -> libc::c_ulong {
        unsafe {
            ffi::webkit_dom_html_input_element_get_width(self.to_glib_none().0)
        }
    }

    fn get_will_validate(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_get_will_validate(self.to_glib_none().0))
        }
    }

    fn is_edited(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_html_input_element_is_edited(self.to_glib_none().0))
        }
    }

    fn select(&self) {
        unsafe {
            ffi::webkit_dom_html_input_element_select(self.to_glib_none().0);
        }
    }

    fn set_accept(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_accept(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_align(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_align(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_alt(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_alt(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    #[cfg(feature = "v2_16")]
    fn set_auto_filled(&self, value: bool) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_auto_filled(self.to_glib_none().0, value.to_glib());
        }
    }

    fn set_autofocus(&self, value: bool) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_autofocus(self.to_glib_none().0, value.to_glib());
        }
    }

    #[cfg(feature = "v2_16")]
    fn set_capture_type(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_capture_type(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_checked(&self, value: bool) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_checked(self.to_glib_none().0, value.to_glib());
        }
    }

    #[cfg(feature = "v2_16")]
    fn set_default_checked(&self, value: bool) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_default_checked(self.to_glib_none().0, value.to_glib());
        }
    }

    fn set_default_value(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_default_value(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_disabled(&self, value: bool) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_disabled(self.to_glib_none().0, value.to_glib());
        }
    }

    #[cfg(feature = "v2_16")]
    fn set_editing_value(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_editing_value(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_files(&self, value: &DOMFileList) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_files(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_height(&self, value: libc::c_ulong) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_height(self.to_glib_none().0, value);
        }
    }

    fn set_indeterminate(&self, value: bool) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_indeterminate(self.to_glib_none().0, value.to_glib());
        }
    }

    fn set_input_type(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_input_type(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_max_length(&self, value: libc::c_long) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::webkit_dom_html_input_element_set_max_length(self.to_glib_none().0, value, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn set_multiple(&self, value: bool) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_multiple(self.to_glib_none().0, value.to_glib());
        }
    }

    fn set_name(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_name(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_read_only(&self, value: bool) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_read_only(self.to_glib_none().0, value.to_glib());
        }
    }

    fn set_size(&self, value: libc::c_ulong) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::webkit_dom_html_input_element_set_size(self.to_glib_none().0, value, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn set_src(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_src(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_use_map(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_use_map(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_value(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_value(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_width(&self, value: libc::c_ulong) {
        unsafe {
            ffi::webkit_dom_html_input_element_set_width(self.to_glib_none().0, value);
        }
    }

    fn set_property_capture(&self, capture: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "capture".to_glib_none().0, Value::from(capture).to_glib_none().0);
        }
    }

    fn set_property_default_checked(&self, default_checked: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "default-checked".to_glib_none().0, Value::from(&default_checked).to_glib_none().0);
        }
    }

    fn get_property_read_only(&self) -> bool {
        let mut value = Value::from(&false);
        unsafe {
            gobject_ffi::g_object_get_property(self.to_glib_none().0, "read-only".to_glib_none().0, value.to_glib_none_mut().0);
        }
        value.get().unwrap()
    }

    fn get_property_type(&self) -> Option<String> {
        let mut value = Value::from(None::<&str>);
        unsafe {
            gobject_ffi::g_object_get_property(self.to_glib_none().0, "type".to_glib_none().0, value.to_glib_none_mut().0);
        }
        value.get()
    }

    fn set_property_type(&self, type_: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "type".to_glib_none().0, Value::from(type_).to_glib_none().0);
        }
    }
}
