// This file was generated by gir (074a1ca+) from gir-files (???)
// DO NOT EDIT

use DOMElement;
use DOMEventTarget;
use DOMHTMLElement;
use DOMNode;
use DOMObject;
use ffi;
use glib::translate::*;

glib_wrapper! {
    pub struct DOMHTMLQuoteElement(Object<ffi::WebKitDOMHTMLQuoteElement>): DOMHTMLElement, DOMElement, DOMNode, DOMObject, DOMEventTarget;

    match fn {
        get_type => || ffi::webkit_dom_html_quote_element_get_type(),
    }
}

impl DOMHTMLQuoteElement {
    pub fn get_cite(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_quote_element_get_cite(self.to_glib_none().0))
        }
    }

    pub fn set_cite(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_quote_element_set_cite(self.to_glib_none().0, value.to_glib_none().0);
        }
    }
}
