// This file was generated by gir (074a1ca+) from gir-files (???)
// DO NOT EDIT

use DOMDOMWindow;
use DOMEvent;
use DOMObject;
use ffi;
use glib::object::IsA;
use glib::translate::*;

glib_wrapper! {
    pub struct DOMUIEvent(Object<ffi::WebKitDOMUIEvent>): DOMEvent, DOMObject;

    match fn {
        get_type => || ffi::webkit_dom_ui_event_get_type(),
    }
}

pub trait DOMUIEventExt {
    //fn get_char_code(&self) -> /*Unimplemented*/Fundamental: Long;

    //fn get_detail(&self) -> /*Unimplemented*/Fundamental: Long;

    //fn get_key_code(&self) -> /*Unimplemented*/Fundamental: Long;

    //fn get_layer_x(&self) -> /*Unimplemented*/Fundamental: Long;

    //fn get_layer_y(&self) -> /*Unimplemented*/Fundamental: Long;

    //fn get_page_x(&self) -> /*Unimplemented*/Fundamental: Long;

    //fn get_page_y(&self) -> /*Unimplemented*/Fundamental: Long;

    fn get_view(&self) -> Option<DOMDOMWindow>;

    //fn init_ui_event(&self, type_: &str, canBubble: bool, cancelable: bool, view: &DOMDOMWindow, detail: /*Unimplemented*/Fundamental: Long);
}

impl<O: IsA<DOMUIEvent>> DOMUIEventExt for O {
    //fn get_char_code(&self) -> /*Unimplemented*/Fundamental: Long {
    //    unsafe { TODO: call ffi::webkit_dom_ui_event_get_char_code() }
    //}

    //fn get_detail(&self) -> /*Unimplemented*/Fundamental: Long {
    //    unsafe { TODO: call ffi::webkit_dom_ui_event_get_detail() }
    //}

    //fn get_key_code(&self) -> /*Unimplemented*/Fundamental: Long {
    //    unsafe { TODO: call ffi::webkit_dom_ui_event_get_key_code() }
    //}

    //fn get_layer_x(&self) -> /*Unimplemented*/Fundamental: Long {
    //    unsafe { TODO: call ffi::webkit_dom_ui_event_get_layer_x() }
    //}

    //fn get_layer_y(&self) -> /*Unimplemented*/Fundamental: Long {
    //    unsafe { TODO: call ffi::webkit_dom_ui_event_get_layer_y() }
    //}

    //fn get_page_x(&self) -> /*Unimplemented*/Fundamental: Long {
    //    unsafe { TODO: call ffi::webkit_dom_ui_event_get_page_x() }
    //}

    //fn get_page_y(&self) -> /*Unimplemented*/Fundamental: Long {
    //    unsafe { TODO: call ffi::webkit_dom_ui_event_get_page_y() }
    //}

    fn get_view(&self) -> Option<DOMDOMWindow> {
        unsafe {
            from_glib_full(ffi::webkit_dom_ui_event_get_view(self.to_glib_none().0))
        }
    }

    //fn init_ui_event(&self, type_: &str, canBubble: bool, cancelable: bool, view: &DOMDOMWindow, detail: /*Unimplemented*/Fundamental: Long) {
    //    unsafe { TODO: call ffi::webkit_dom_ui_event_init_ui_event() }
    //}
}
