// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use DOMEventTarget;
use DOMNode;
use DOMObject;
use ffi;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct DOMEntityReference(Object<ffi::WebKitDOMEntityReference, ffi::WebKitDOMEntityReferenceClass, DOMEntityReferenceClass>) @extends DOMNode, DOMObject, @implements DOMEventTarget;

    match fn {
        get_type => || ffi::webkit_dom_entity_reference_get_type(),
    }
}

impl DOMEntityReference {}

pub const NONE_DOM_ENTITY_REFERENCE: Option<&DOMEntityReference> = None;

impl fmt::Display for DOMEntityReference {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "DOMEntityReference")
    }
}
