// This file was generated by gir (f00d658) from gir-files (1069259)
// DO NOT EDIT

use DOMElement;
use DOMEventTarget;
use DOMHTMLElement;
use DOMNode;
use DOMObject;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DOMHTMLTitleElement(Object<ffi::WebKitDOMHTMLTitleElement>): DOMHTMLElement, DOMElement, DOMNode, DOMObject, DOMEventTarget;

    match fn {
        get_type => || ffi::webkit_dom_html_title_element_get_type(),
    }
}

pub trait DOMHTMLTitleElementExt {
    fn get_text(&self) -> Option<String>;

    fn set_text(&self, value: &str);
}

impl<O: IsA<DOMHTMLTitleElement>> DOMHTMLTitleElementExt for O {
    fn get_text(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_title_element_get_text(self.to_glib_none().0))
        }
    }

    fn set_text(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_title_element_set_text(self.to_glib_none().0, value.to_glib_none().0);
        }
    }
}
