// This file was generated by gir (e95e5d8) from gir-files (857b8f5)
// DO NOT EDIT

use DOMEventTarget;
use DOMNode;
use DOMObject;
use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DOMEntityReference(Object<ffi::WebKitDOMEntityReference>): DOMNode, DOMObject, DOMEventTarget;

    match fn {
        get_type => || ffi::webkit_dom_entity_reference_get_type(),
    }
}

impl DOMEntityReference {}
