// This file was generated by gir (0f7cd61) from gir-files (0bcaef9)
// DO NOT EDIT

use DOMElement;
use DOMEventTarget;
use DOMHTMLElement;
use DOMHTMLFormElement;
use DOMNode;
use DOMObject;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DOMHTMLLegendElement(Object<ffi::WebKitDOMHTMLLegendElement>): DOMHTMLElement, DOMElement, DOMNode, DOMObject, DOMEventTarget;

    match fn {
        get_type => || ffi::webkit_dom_html_legend_element_get_type(),
    }
}

pub trait DOMHTMLLegendElementExt {
    fn get_align(&self) -> Option<String>;

    fn get_form(&self) -> Option<DOMHTMLFormElement>;

    fn set_align(&self, value: &str);
}

impl<O: IsA<DOMHTMLLegendElement>> DOMHTMLLegendElementExt for O {
    fn get_align(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_html_legend_element_get_align(self.to_glib_none().0))
        }
    }

    fn get_form(&self) -> Option<DOMHTMLFormElement> {
        unsafe {
            from_glib_none(ffi::webkit_dom_html_legend_element_get_form(self.to_glib_none().0))
        }
    }

    fn set_align(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_html_legend_element_set_align(self.to_glib_none().0, value.to_glib_none().0);
        }
    }
}
