// This file was generated by gir (074a1ca+) from gir-files (???)
// DO NOT EDIT

use DOMAttr;
use DOMCDATASection;
use DOMCSSStyleDeclaration;
use DOMComment;
use DOMDOMImplementation;
use DOMDOMWindow;
use DOMDocumentFragment;
use DOMDocumentType;
use DOMElement;
use DOMEntityReference;
use DOMEvent;
use DOMHTMLCollection;
use DOMHTMLElement;
use DOMHTMLHeadElement;
use DOMNode;
use DOMNodeList;
use DOMObject;
use DOMProcessingInstruction;
use DOMRange;
use DOMStyleSheetList;
use DOMText;
use Error;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use std::ptr;

glib_wrapper! {
    pub struct DOMDocument(Object<ffi::WebKitDOMDocument>): DOMNode, DOMObject;

    match fn {
        get_type => || ffi::webkit_dom_document_get_type(),
    }
}

pub trait DOMDocumentExt {
    fn adopt_node<T: IsA<DOMNode>>(&self, source: &T) -> Result<DOMNode, Error>;

    fn create_attribute(&self, name: &str) -> Result<DOMAttr, Error>;

    fn create_attribute_ns(&self, namespaceURI: Option<&str>, qualifiedName: &str) -> Result<DOMAttr, Error>;

    fn create_cdata_section(&self, data: &str) -> Result<DOMCDATASection, Error>;

    fn create_comment(&self, data: &str) -> Option<DOMComment>;

    fn create_css_style_declaration(&self) -> Option<DOMCSSStyleDeclaration>;

    fn create_document_fragment(&self) -> Option<DOMDocumentFragment>;

    fn create_element(&self, tagName: &str) -> Result<DOMElement, Error>;

    fn create_element_ns(&self, namespaceURI: Option<&str>, qualifiedName: &str) -> Result<DOMElement, Error>;

    fn create_entity_reference(&self, name: Option<&str>) -> Result<DOMEntityReference, Error>;

    fn create_event(&self, eventType: &str) -> Result<DOMEvent, Error>;

    //fn create_expression<T: IsA</*Ignored*/DOMXPathNSResolver>>(&self, expression: &str, resolver: &T) -> Result<DOMXPathExpression, Error>;

    //fn create_node_iterator<T: IsA<DOMNode>, U: IsA</*Ignored*/DOMNodeFilter>>(&self, root: &T, whatToShow: u64, filter: Option<&U>, expandEntityReferences: bool) -> Result<DOMNodeIterator, Error>;

    //fn create_ns_resolver<T: IsA<DOMNode>>(&self, nodeResolver: &T) -> /*Ignored*/Option<DOMXPathNSResolver>;

    fn create_processing_instruction(&self, target: &str, data: &str) -> Result<DOMProcessingInstruction, Error>;

    fn create_range(&self) -> Option<DOMRange>;

    fn create_text_node(&self, data: &str) -> Option<DOMText>;

    //fn create_tree_walker<T: IsA<DOMNode>, U: IsA</*Ignored*/DOMNodeFilter>>(&self, root: &T, whatToShow: u64, filter: Option<&U>, expandEntityReferences: bool) -> Result<DOMTreeWalker, Error>;

    fn element_from_point(&self, x: i64, y: i64) -> Option<DOMElement>;

    //fn evaluate<T: IsA<DOMNode>, U: IsA</*Ignored*/DOMXPathNSResolver>>(&self, expression: &str, contextNode: &T, resolver: Option<&U>, type_: /*Unimplemented*/Fundamental: UShort, inResult: Option<&DOMXPathResult>) -> Result<DOMXPathResult, Error>;

    fn exec_command(&self, command: &str, userInterface: bool, value: &str) -> bool;

    fn get_active_element(&self) -> Option<DOMElement>;

    fn get_anchors(&self) -> Option<DOMHTMLCollection>;

    fn get_applets(&self) -> Option<DOMHTMLCollection>;

    fn get_body(&self) -> Option<DOMHTMLElement>;

    fn get_character_set(&self) -> Option<String>;

    fn get_charset(&self) -> Option<String>;

    fn get_cookie(&self) -> Result<String, Error>;

    fn get_default_charset(&self) -> Option<String>;

    fn get_default_view(&self) -> Option<DOMDOMWindow>;

    fn get_doctype(&self) -> Option<DOMDocumentType>;

    fn get_document_element(&self) -> Option<DOMElement>;

    fn get_document_uri(&self) -> Option<String>;

    fn get_domain(&self) -> Option<String>;

    fn get_element_by_id(&self, elementId: &str) -> Option<DOMElement>;

    fn get_elements_by_class_name(&self, class_name: &str) -> Option<DOMNodeList>;

    #[cfg(feature = "v2_12")]
    fn get_elements_by_class_name_as_html_collection(&self, classNames: &str) -> Option<DOMHTMLCollection>;

    fn get_elements_by_name(&self, elementName: &str) -> Option<DOMNodeList>;

    fn get_elements_by_tag_name(&self, tag_name: &str) -> Option<DOMNodeList>;

    #[cfg(feature = "v2_12")]
    fn get_elements_by_tag_name_as_html_collection(&self, tagname: &str) -> Option<DOMHTMLCollection>;

    fn get_elements_by_tag_name_ns(&self, namespace_uri: &str, tag_name: &str) -> Option<DOMNodeList>;

    #[cfg(feature = "v2_12")]
    fn get_elements_by_tag_name_ns_as_html_collection(&self, namespaceURI: &str, localName: &str) -> Option<DOMHTMLCollection>;

    fn get_forms(&self) -> Option<DOMHTMLCollection>;

    fn get_head(&self) -> Option<DOMHTMLHeadElement>;

    fn get_images(&self) -> Option<DOMHTMLCollection>;

    fn get_implementation(&self) -> Option<DOMDOMImplementation>;

    fn get_input_encoding(&self) -> Option<String>;

    fn get_last_modified(&self) -> Option<String>;

    fn get_links(&self) -> Option<DOMHTMLCollection>;

    fn get_override_style<T: IsA<DOMElement>>(&self, element: &T, pseudoElement: Option<&str>) -> Option<DOMCSSStyleDeclaration>;

    fn get_preferred_stylesheet_set(&self) -> Option<String>;

    fn get_ready_state(&self) -> Option<String>;

    fn get_referrer(&self) -> Option<String>;

    fn get_selected_stylesheet_set(&self) -> Option<String>;

    fn get_style_sheets(&self) -> Option<DOMStyleSheetList>;

    fn get_title(&self) -> Option<String>;

    fn get_url(&self) -> Option<String>;

    fn get_xml_encoding(&self) -> Option<String>;

    fn get_xml_standalone(&self) -> bool;

    fn get_xml_version(&self) -> Option<String>;

    fn has_focus(&self) -> bool;

    fn import_node<T: IsA<DOMNode>>(&self, importedNode: &T, deep: bool) -> Result<DOMNode, Error>;

    fn query_command_enabled(&self, command: &str) -> bool;

    fn query_command_indeterm(&self, command: &str) -> bool;

    fn query_command_state(&self, command: &str) -> bool;

    fn query_command_supported(&self, command: &str) -> bool;

    fn query_command_value(&self, command: &str) -> Option<String>;

    fn query_selector(&self, selectors: &str) -> Result<DOMElement, Error>;

    fn query_selector_all(&self, selectors: &str) -> Result<DOMNodeList, Error>;

    fn set_body<T: IsA<DOMHTMLElement>>(&self, value: &T) -> Result<(), Error>;

    fn set_charset(&self, value: &str);

    fn set_cookie(&self, value: &str) -> Result<(), Error>;

    fn set_document_uri(&self, value: &str);

    fn set_selected_stylesheet_set(&self, value: &str);

    fn set_title(&self, value: &str);

    fn set_xml_standalone(&self, value: bool) -> Result<(), Error>;

    fn set_xml_version(&self, value: &str) -> Result<(), Error>;
}

impl<O: IsA<DOMDocument>> DOMDocumentExt for O {
    fn adopt_node<T: IsA<DOMNode>>(&self, source: &T) -> Result<DOMNode, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_adopt_node(self.to_glib_none().0, source.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn create_attribute(&self, name: &str) -> Result<DOMAttr, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_create_attribute(self.to_glib_none().0, name.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn create_attribute_ns(&self, namespaceURI: Option<&str>, qualifiedName: &str) -> Result<DOMAttr, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_create_attribute_ns(self.to_glib_none().0, namespaceURI.to_glib_none().0, qualifiedName.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn create_cdata_section(&self, data: &str) -> Result<DOMCDATASection, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_create_cdata_section(self.to_glib_none().0, data.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn create_comment(&self, data: &str) -> Option<DOMComment> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_create_comment(self.to_glib_none().0, data.to_glib_none().0))
        }
    }

    fn create_css_style_declaration(&self) -> Option<DOMCSSStyleDeclaration> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_create_css_style_declaration(self.to_glib_none().0))
        }
    }

    fn create_document_fragment(&self) -> Option<DOMDocumentFragment> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_create_document_fragment(self.to_glib_none().0))
        }
    }

    fn create_element(&self, tagName: &str) -> Result<DOMElement, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_create_element(self.to_glib_none().0, tagName.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn create_element_ns(&self, namespaceURI: Option<&str>, qualifiedName: &str) -> Result<DOMElement, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_create_element_ns(self.to_glib_none().0, namespaceURI.to_glib_none().0, qualifiedName.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn create_entity_reference(&self, name: Option<&str>) -> Result<DOMEntityReference, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_create_entity_reference(self.to_glib_none().0, name.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn create_event(&self, eventType: &str) -> Result<DOMEvent, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_create_event(self.to_glib_none().0, eventType.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    //fn create_expression<T: IsA</*Ignored*/DOMXPathNSResolver>>(&self, expression: &str, resolver: &T) -> Result<DOMXPathExpression, Error> {
    //    unsafe { TODO: call ffi::webkit_dom_document_create_expression() }
    //}

    //fn create_node_iterator<T: IsA<DOMNode>, U: IsA</*Ignored*/DOMNodeFilter>>(&self, root: &T, whatToShow: u64, filter: Option<&U>, expandEntityReferences: bool) -> Result<DOMNodeIterator, Error> {
    //    unsafe { TODO: call ffi::webkit_dom_document_create_node_iterator() }
    //}

    //fn create_ns_resolver<T: IsA<DOMNode>>(&self, nodeResolver: &T) -> /*Ignored*/Option<DOMXPathNSResolver> {
    //    unsafe { TODO: call ffi::webkit_dom_document_create_ns_resolver() }
    //}

    fn create_processing_instruction(&self, target: &str, data: &str) -> Result<DOMProcessingInstruction, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_create_processing_instruction(self.to_glib_none().0, target.to_glib_none().0, data.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn create_range(&self) -> Option<DOMRange> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_create_range(self.to_glib_none().0))
        }
    }

    fn create_text_node(&self, data: &str) -> Option<DOMText> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_create_text_node(self.to_glib_none().0, data.to_glib_none().0))
        }
    }

    //fn create_tree_walker<T: IsA<DOMNode>, U: IsA</*Ignored*/DOMNodeFilter>>(&self, root: &T, whatToShow: u64, filter: Option<&U>, expandEntityReferences: bool) -> Result<DOMTreeWalker, Error> {
    //    unsafe { TODO: call ffi::webkit_dom_document_create_tree_walker() }
    //}

    fn element_from_point(&self, x: i64, y: i64) -> Option<DOMElement> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_element_from_point(self.to_glib_none().0, x, y))
        }
    }

    //fn evaluate<T: IsA<DOMNode>, U: IsA</*Ignored*/DOMXPathNSResolver>>(&self, expression: &str, contextNode: &T, resolver: Option<&U>, type_: /*Unimplemented*/Fundamental: UShort, inResult: Option<&DOMXPathResult>) -> Result<DOMXPathResult, Error> {
    //    unsafe { TODO: call ffi::webkit_dom_document_evaluate() }
    //}

    fn exec_command(&self, command: &str, userInterface: bool, value: &str) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_document_exec_command(self.to_glib_none().0, command.to_glib_none().0, userInterface.to_glib(), value.to_glib_none().0))
        }
    }

    fn get_active_element(&self) -> Option<DOMElement> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_get_active_element(self.to_glib_none().0))
        }
    }

    fn get_anchors(&self) -> Option<DOMHTMLCollection> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_anchors(self.to_glib_none().0))
        }
    }

    fn get_applets(&self) -> Option<DOMHTMLCollection> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_applets(self.to_glib_none().0))
        }
    }

    fn get_body(&self) -> Option<DOMHTMLElement> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_get_body(self.to_glib_none().0))
        }
    }

    fn get_character_set(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_character_set(self.to_glib_none().0))
        }
    }

    fn get_charset(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_charset(self.to_glib_none().0))
        }
    }

    fn get_cookie(&self) -> Result<String, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_get_cookie(self.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn get_default_charset(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_default_charset(self.to_glib_none().0))
        }
    }

    fn get_default_view(&self) -> Option<DOMDOMWindow> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_default_view(self.to_glib_none().0))
        }
    }

    fn get_doctype(&self) -> Option<DOMDocumentType> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_get_doctype(self.to_glib_none().0))
        }
    }

    fn get_document_element(&self) -> Option<DOMElement> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_get_document_element(self.to_glib_none().0))
        }
    }

    fn get_document_uri(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_document_uri(self.to_glib_none().0))
        }
    }

    fn get_domain(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_domain(self.to_glib_none().0))
        }
    }

    fn get_element_by_id(&self, elementId: &str) -> Option<DOMElement> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_get_element_by_id(self.to_glib_none().0, elementId.to_glib_none().0))
        }
    }

    fn get_elements_by_class_name(&self, class_name: &str) -> Option<DOMNodeList> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_elements_by_class_name(self.to_glib_none().0, class_name.to_glib_none().0))
        }
    }

    #[cfg(feature = "v2_12")]
    fn get_elements_by_class_name_as_html_collection(&self, classNames: &str) -> Option<DOMHTMLCollection> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_elements_by_class_name_as_html_collection(self.to_glib_none().0, classNames.to_glib_none().0))
        }
    }

    fn get_elements_by_name(&self, elementName: &str) -> Option<DOMNodeList> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_elements_by_name(self.to_glib_none().0, elementName.to_glib_none().0))
        }
    }

    fn get_elements_by_tag_name(&self, tag_name: &str) -> Option<DOMNodeList> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_elements_by_tag_name(self.to_glib_none().0, tag_name.to_glib_none().0))
        }
    }

    #[cfg(feature = "v2_12")]
    fn get_elements_by_tag_name_as_html_collection(&self, tagname: &str) -> Option<DOMHTMLCollection> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_elements_by_tag_name_as_html_collection(self.to_glib_none().0, tagname.to_glib_none().0))
        }
    }

    fn get_elements_by_tag_name_ns(&self, namespace_uri: &str, tag_name: &str) -> Option<DOMNodeList> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_elements_by_tag_name_ns(self.to_glib_none().0, namespace_uri.to_glib_none().0, tag_name.to_glib_none().0))
        }
    }

    #[cfg(feature = "v2_12")]
    fn get_elements_by_tag_name_ns_as_html_collection(&self, namespaceURI: &str, localName: &str) -> Option<DOMHTMLCollection> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_elements_by_tag_name_ns_as_html_collection(self.to_glib_none().0, namespaceURI.to_glib_none().0, localName.to_glib_none().0))
        }
    }

    fn get_forms(&self) -> Option<DOMHTMLCollection> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_forms(self.to_glib_none().0))
        }
    }

    fn get_head(&self) -> Option<DOMHTMLHeadElement> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_get_head(self.to_glib_none().0))
        }
    }

    fn get_images(&self) -> Option<DOMHTMLCollection> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_images(self.to_glib_none().0))
        }
    }

    fn get_implementation(&self) -> Option<DOMDOMImplementation> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_implementation(self.to_glib_none().0))
        }
    }

    fn get_input_encoding(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_input_encoding(self.to_glib_none().0))
        }
    }

    fn get_last_modified(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_last_modified(self.to_glib_none().0))
        }
    }

    fn get_links(&self) -> Option<DOMHTMLCollection> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_links(self.to_glib_none().0))
        }
    }

    fn get_override_style<T: IsA<DOMElement>>(&self, element: &T, pseudoElement: Option<&str>) -> Option<DOMCSSStyleDeclaration> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_override_style(self.to_glib_none().0, element.to_glib_none().0, pseudoElement.to_glib_none().0))
        }
    }

    fn get_preferred_stylesheet_set(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_preferred_stylesheet_set(self.to_glib_none().0))
        }
    }

    fn get_ready_state(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_ready_state(self.to_glib_none().0))
        }
    }

    fn get_referrer(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_referrer(self.to_glib_none().0))
        }
    }

    fn get_selected_stylesheet_set(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_selected_stylesheet_set(self.to_glib_none().0))
        }
    }

    fn get_style_sheets(&self) -> Option<DOMStyleSheetList> {
        unsafe {
            from_glib_none(ffi::webkit_dom_document_get_style_sheets(self.to_glib_none().0))
        }
    }

    fn get_title(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_title(self.to_glib_none().0))
        }
    }

    fn get_url(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_url(self.to_glib_none().0))
        }
    }

    fn get_xml_encoding(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_xml_encoding(self.to_glib_none().0))
        }
    }

    fn get_xml_standalone(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_document_get_xml_standalone(self.to_glib_none().0))
        }
    }

    fn get_xml_version(&self) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_get_xml_version(self.to_glib_none().0))
        }
    }

    fn has_focus(&self) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_document_has_focus(self.to_glib_none().0))
        }
    }

    fn import_node<T: IsA<DOMNode>>(&self, importedNode: &T, deep: bool) -> Result<DOMNode, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_import_node(self.to_glib_none().0, importedNode.to_glib_none().0, deep.to_glib(), &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn query_command_enabled(&self, command: &str) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_document_query_command_enabled(self.to_glib_none().0, command.to_glib_none().0))
        }
    }

    fn query_command_indeterm(&self, command: &str) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_document_query_command_indeterm(self.to_glib_none().0, command.to_glib_none().0))
        }
    }

    fn query_command_state(&self, command: &str) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_document_query_command_state(self.to_glib_none().0, command.to_glib_none().0))
        }
    }

    fn query_command_supported(&self, command: &str) -> bool {
        unsafe {
            from_glib(ffi::webkit_dom_document_query_command_supported(self.to_glib_none().0, command.to_glib_none().0))
        }
    }

    fn query_command_value(&self, command: &str) -> Option<String> {
        unsafe {
            from_glib_full(ffi::webkit_dom_document_query_command_value(self.to_glib_none().0, command.to_glib_none().0))
        }
    }

    fn query_selector(&self, selectors: &str) -> Result<DOMElement, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_query_selector(self.to_glib_none().0, selectors.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_none(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn query_selector_all(&self, selectors: &str) -> Result<DOMNodeList, Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::webkit_dom_document_query_selector_all(self.to_glib_none().0, selectors.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn set_body<T: IsA<DOMHTMLElement>>(&self, value: &T) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::webkit_dom_document_set_body(self.to_glib_none().0, value.to_glib_none().0, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn set_charset(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_document_set_charset(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_cookie(&self, value: &str) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::webkit_dom_document_set_cookie(self.to_glib_none().0, value.to_glib_none().0, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn set_document_uri(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_document_set_document_uri(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_selected_stylesheet_set(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_document_set_selected_stylesheet_set(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_title(&self, value: &str) {
        unsafe {
            ffi::webkit_dom_document_set_title(self.to_glib_none().0, value.to_glib_none().0);
        }
    }

    fn set_xml_standalone(&self, value: bool) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::webkit_dom_document_set_xml_standalone(self.to_glib_none().0, value.to_glib(), &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn set_xml_version(&self, value: &str) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::webkit_dom_document_set_xml_version(self.to_glib_none().0, value.to_glib_none().0, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }
}
